### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by eric-unc** [COMP523TeamD/HeadCircumferenceTool#10]
See log [here](https://gist.github.com/eric-unc/5442f5cdbe84941c9069c8bf40b0253b). Seems to be an issue with `matplotlib`.

Part of the log recommends throwing in `--use-pep517` as an arg but it [has an issue building wheels instead](https://gist.github.com/eric-unc/29cd6c047bc88b8e253f3abc24f768a2).

**Comment by eric-unc** [comment]
I could install `matplotlib` using just `pip install matplotlib`; seems like it's just this outdated version of it (3.5.2 instead of 3.7.1) that is an issue.

**Comment by eric-unc** [comment]
@jesse-wei if matplotlib isn't used outside of the "playground" then you should probably remove it from `requirements.txt`

**Comment by jesse-wei** [comment]
Removed
